config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :black_accounts
  resources :blue_accounts
  resources :red_accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/black_account.rb
class BlackAccount < ApplicationRecord
  belongs_to :user
end

app/controllers/black_accounts_controller.rb
class BlackAccountsController < ApplicationController
  before_action :set_black_account, only: [:show, :edit, :update, :destroy]

  # GET /black_accounts
  # GET /black_accounts.json
  def index
    @black_accounts = BlackAccount.all
  end

  # GET /black_accounts/1
  # GET /black_accounts/1.json
  def show
  end

  # GET /black_accounts/new
  def new
    @black_account = BlackAccount.new
  end

  # GET /black_accounts/1/edit
  def edit
  end

  # POST /black_accounts
  # POST /black_accounts.json
  def create
    @black_account = BlackAccount.new(black_account_params)

    respond_to do |format|
      if @black_account.save
        format.html { redirect_to @black_account, notice: 'Black account was successfully created.' }
        format.json { render :show, status: :created, location: @black_account }
      else
        format.html { render :new }
        format.json { render json: @black_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /black_accounts/1
  # PATCH/PUT /black_accounts/1.json
  def update
    respond_to do |format|
      if @black_account.update(black_account_params)
        format.html { redirect_to @black_account, notice: 'Black account was successfully updated.' }
        format.json { render :show, status: :ok, location: @black_account }
      else
        format.html { render :edit }
        format.json { render json: @black_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /black_accounts/1
  # DELETE /black_accounts/1.json
  def destroy
    @black_account.destroy
    respond_to do |format|
      format.html { redirect_to black_accounts_url, notice: 'Black account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_black_account
      @black_account = BlackAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def black_account_params
      params.require(:black_account).permit(:Accountid, :name, :accountBalance, :accountLimit, :apr, :userId)
    end
end

app/helpers/black_accounts_helper.rb
module BlackAccountsHelper
end

app/views/black_accounts/_form.html.erb
<%= form_with(model: black_account, local: true) do |form| %>
  <% if black_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(black_account.errors.count, "error") %> prohibited this black_account from being saved:</h2>

      <ul>
      <% black_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Accountid %>
    <%= form.number_field :Accountid, id: :black_account_Accountid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :black_account_name %>
  </div>

  <div class="field">
    <%= form.label :accountBalance %>
    <%= form.number_field :accountBalance, id: :black_account_accountBalance %>
  </div>

  <div class="field">
    <%= form.label :accountLimit %>
    <%= form.number_field :accountLimit, id: :black_account_accountLimit %>
  </div>

  <div class="field">
    <%= form.label :apr %>
    <%= form.number_field :apr, id: :black_account_apr %>
  </div>

  <div class="field">
    <%= form.label :userId %>
    <%= form.number_field :userId, id: :black_account_userId %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/black_accounts/edit.html.erb
<h1>Editing Black Account</h1>

<%= render 'form', black_account: @black_account %>

<%= link_to 'Show', @black_account %> |
<%= link_to 'Back', black_accounts_path %>

app/views/black_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Black Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Accountid</th>
      <th>Name</th>
      <th>Accountbalance</th>
      <th>Accountlimit</th>
      <th>Apr</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @black_accounts.each do |black_account| %>
      <tr>
        <td><%= black_account.Accountid %></td>
        <td><%= black_account.name %></td>
        <td><%= black_account.accountBalance %></td>
        <td><%= black_account.accountLimit %></td>
        <td><%= black_account.apr %></td>
        <td><%= black_account.userId %></td>
        <td><%= link_to 'Show', black_account %></td>
        <td><%= link_to 'Edit', edit_black_account_path(black_account) %></td>
        <td><%= link_to 'Destroy', black_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Black Account', new_black_account_path %>

app/views/black_accounts/new.html.erb
<h1>New Black Account</h1>

<%= render 'form', black_account: @black_account %>

<%= link_to 'Back', black_accounts_path %>

app/views/black_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accountid:</strong>
  <%= @black_account.Accountid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @black_account.name %>
</p>

<p>
  <strong>Accountbalance:</strong>
  <%= @black_account.accountBalance %>
</p>

<p>
  <strong>Accountlimit:</strong>
  <%= @black_account.accountLimit %>
</p>

<p>
  <strong>Apr:</strong>
  <%= @black_account.apr %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @black_account.userId %>
</p>

<%= link_to 'Edit', edit_black_account_path(@black_account) %> |
<%= link_to 'Back', black_accounts_path %>