config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :black_accounts
  resources :blue_accounts
  resources :red_accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blue_account.rb
class BlueAccount < ApplicationRecord
  belongs_to :user
end

app/controllers/blue_accounts_controller.rb
class BlueAccountsController < ApplicationController
  before_action :set_blue_account, only: [:show, :edit, :update, :destroy]

  # GET /blue_accounts
  # GET /blue_accounts.json
  def index
    @blue_accounts = BlueAccount.all
  end

  # GET /blue_accounts/1
  # GET /blue_accounts/1.json
  def show
  end

  # GET /blue_accounts/new
  def new
    @blue_account = BlueAccount.new
  end

  # GET /blue_accounts/1/edit
  def edit
  end

  # POST /blue_accounts
  # POST /blue_accounts.json
  def create
    @blue_account = BlueAccount.new(blue_account_params)

    respond_to do |format|
      if @blue_account.save
        format.html { redirect_to @blue_account, notice: 'Blue account was successfully created.' }
        format.json { render :show, status: :created, location: @blue_account }
      else
        format.html { render :new }
        format.json { render json: @blue_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blue_accounts/1
  # PATCH/PUT /blue_accounts/1.json
  def update
    respond_to do |format|
      if @blue_account.update(blue_account_params)
        format.html { redirect_to @blue_account, notice: 'Blue account was successfully updated.' }
        format.json { render :show, status: :ok, location: @blue_account }
      else
        format.html { render :edit }
        format.json { render json: @blue_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blue_accounts/1
  # DELETE /blue_accounts/1.json
  def destroy
    @blue_account.destroy
    respond_to do |format|
      format.html { redirect_to blue_accounts_url, notice: 'Blue account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blue_account
      @blue_account = BlueAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blue_account_params
      params.require(:blue_account).permit(:Accountid, :name, :accountBalance, :Address, :paymentDate, :userID, :contactInformation)
    end
end

app/helpers/blue_accounts_helper.rb
module BlueAccountsHelper
end

app/views/blue_accounts/_form.html.erb
<%= form_with(model: blue_account, local: true) do |form| %>
  <% if blue_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blue_account.errors.count, "error") %> prohibited this blue_account from being saved:</h2>

      <ul>
      <% blue_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Accountid %>
    <%= form.number_field :Accountid, id: :blue_account_Accountid %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :blue_account_name %>
  </div>

  <div class="field">
    <%= form.label :accountBalance %>
    <%= form.number_field :accountBalance, id: :blue_account_accountBalance %>
  </div>

  <div class="field">
    <%= form.label :Address %>
    <%= form.text_field :Address, id: :blue_account_Address %>
  </div>

  <div class="field">
    <%= form.label :paymentDate %>
    <%= form.date_select :paymentDate, id: :blue_account_paymentDate %>
  </div>

  <div class="field">
    <%= form.label :userID %>
    <%= form.number_field :userID, id: :blue_account_userID %>
  </div>

  <div class="field">
    <%= form.label :contactInformation %>
    <%= form.text_field :contactInformation, id: :blue_account_contactInformation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blue_accounts/edit.html.erb
<h1>Editing Blue Account</h1>

<%= render 'form', blue_account: @blue_account %>

<%= link_to 'Show', @blue_account %> |
<%= link_to 'Back', blue_accounts_path %>

app/views/blue_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blue Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Accountid</th>
      <th>Name</th>
      <th>Accountbalance</th>
      <th>Address</th>
      <th>Paymentdate</th>
      <th>Userid</th>
      <th>Contactinformation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blue_accounts.each do |blue_account| %>
      <tr>
        <td><%= blue_account.Accountid %></td>
        <td><%= blue_account.name %></td>
        <td><%= blue_account.accountBalance %></td>
        <td><%= blue_account.Address %></td>
        <td><%= blue_account.paymentDate %></td>
        <td><%= blue_account.userID %></td>
        <td><%= blue_account.contactInformation %></td>
        <td><%= link_to 'Show', blue_account %></td>
        <td><%= link_to 'Edit', edit_blue_account_path(blue_account) %></td>
        <td><%= link_to 'Destroy', blue_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blue Account', new_blue_account_path %>

app/views/blue_accounts/new.html.erb
<h1>New Blue Account</h1>

<%= render 'form', blue_account: @blue_account %>

<%= link_to 'Back', blue_accounts_path %>

app/views/blue_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Accountid:</strong>
  <%= @blue_account.Accountid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @blue_account.name %>
</p>

<p>
  <strong>Accountbalance:</strong>
  <%= @blue_account.accountBalance %>
</p>

<p>
  <strong>Address:</strong>
  <%= @blue_account.Address %>
</p>

<p>
  <strong>Paymentdate:</strong>
  <%= @blue_account.paymentDate %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @blue_account.userID %>
</p>

<p>
  <strong>Contactinformation:</strong>
  <%= @blue_account.contactInformation %>
</p>

<%= link_to 'Edit', edit_blue_account_path(@blue_account) %> |
<%= link_to 'Back', blue_accounts_path %>