config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :black_accounts
  resources :blue_accounts
  resources :red_accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/red_account.rb
  class RedAccount < ApplicationRecord
  belongs_to :user
end

app/controllers/red_accounts_controller.rb
class RedAccountsController < ApplicationController
  before_action :set_red_account, only: [:show, :edit, :update, :destroy]

  # GET /red_accounts
  # GET /red_accounts.json
  def index
    @red_accounts = RedAccount.all
  end

  # GET /red_accounts/1
  # GET /red_accounts/1.json
  def show
  end

  # GET /red_accounts/new
  def new
    @red_account = RedAccount.new
  end

  # GET /red_accounts/1/edit
  def edit
  end

  # POST /red_accounts
  # POST /red_accounts.json
  def create
    @red_account = RedAccount.new(red_account_params)

    respond_to do |format|
      if @red_account.save
        format.html { redirect_to @red_account, notice: 'Red account was successfully created.' }
        format.json { render :show, status: :created, location: @red_account }
      else
        format.html { render :new }
        format.json { render json: @red_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /red_accounts/1
  # PATCH/PUT /red_accounts/1.json
  def update
    respond_to do |format|
      if @red_account.update(red_account_params)
        format.html { redirect_to @red_account, notice: 'Red account was successfully updated.' }
        format.json { render :show, status: :ok, location: @red_account }
      else
        format.html { render :edit }
        format.json { render json: @red_account.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /red_accounts/1
  # DELETE /red_accounts/1.json
  def destroy
    @red_account.destroy
    respond_to do |format|
      format.html { redirect_to red_accounts_url, notice: 'Red account was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_red_account
      @red_account = RedAccount.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def red_account_params
      params.require(:red_account).permit(:id, :name, :accountBalance, :accountLimit, :paymentDate, :userID, :integer, :apr)
    end
end

app/helpers/red_accounts_helper.rb
module RedAccountsHelper
end

app/views/red_accounts/_form.html.erb
<%= form_with(model: red_account, local: true) do |form| %>
  <% if red_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(red_account.errors.count, "error") %> prohibited this red_account from being saved:</h2>

      <ul>
      <% red_account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :id %>
    <%= form.number_field :id, id: :red_account_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :red_account_name %>
  </div>

  <div class="field">
    <%= form.label :accountBalance %>
    <%= form.number_field :accountBalance, id: :red_account_accountBalance %>
  </div>

  <div class="field">
    <%= form.label :accountLimit %>
    <%= form.number_field :accountLimit, id: :red_account_accountLimit %>
  </div>

  <div class="field">
    <%= form.label :paymentDate %>
    <%= form.date_select :paymentDate, id: :red_account_paymentDate %>
  </div>

  <div class="field">
    <%= form.label :userID %>
    <%= form.text_field :userID, id: :red_account_userID %>
  </div>

  <div class="field">
    <%= form.label :integer %>
    <%= form.text_field :integer, id: :red_account_integer %>
  </div>

  <div class="field">
    <%= form.label :apr %>
    <%= form.text_field :apr, id: :red_account_apr %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/red_accounts/edit.html.erb
<h1>Editing Red Account</h1>

<%= render 'form', red_account: @red_account %>

<%= link_to 'Show', @red_account %> |
<%= link_to 'Back', red_accounts_path %>

app/views/red_accounts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Red Accounts</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Accountbalance</th>
      <th>Accountlimit</th>
      <th>Paymentdate</th>
      <th>Userid</th>
      <th>Integer</th>
      <th>Apr</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @red_accounts.each do |red_account| %>
      <tr>
        <td><%= red_account.id %></td>
        <td><%= red_account.name %></td>
        <td><%= red_account.accountBalance %></td>
        <td><%= red_account.accountLimit %></td>
        <td><%= red_account.paymentDate %></td>
        <td><%= red_account.userID %></td>
        <td><%= red_account.integer %></td>
        <td><%= red_account.apr %></td>
        <td><%= link_to 'Show', red_account %></td>
        <td><%= link_to 'Edit', edit_red_account_path(red_account) %></td>
        <td><%= link_to 'Destroy', red_account, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Red Account', new_red_account_path %>

app/views/red_accounts/new.html.erb
<h1>New Red Account</h1>

<%= render 'form', red_account: @red_account %>

<%= link_to 'Back', red_accounts_path %>

app/views/red_accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @red_account.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @red_account.name %>
</p>

<p>
  <strong>Accountbalance:</strong>
  <%= @red_account.accountBalance %>
</p>

<p>
  <strong>Accountlimit:</strong>
  <%= @red_account.accountLimit %>
</p>

<p>
  <strong>Paymentdate:</strong>
  <%= @red_account.paymentDate %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @red_account.userID %>
</p>

<p>
  <strong>Integer:</strong>
  <%= @red_account.integer %>
</p>

<p>
  <strong>Apr:</strong>
  <%= @red_account.apr %>
</p>

<%= link_to 'Edit', edit_red_account_path(@red_account) %> |
<%= link_to 'Back', red_accounts_path %>